// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T_G.ECommerce.DataAccess.Context;

#nullable disable

namespace T_G.ECommerce.DataAccess.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    partial class ECommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("T_G.ECommerce.Entities.Concrete.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3637),
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3648),
                            Name = "Book"
                        },
                        new
                        {
                            Id = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3649),
                            Name = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3650),
                            Name = "Cosmetic"
                        },
                        new
                        {
                            Id = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3651),
                            Name = "Furniture"
                        });
                });

            modelBuilder.Entity("T_G.ECommerce.Entities.Concrete.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca69a7a6-0856-466b-8f97-0e9d5c81353d"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3717),
                            Description = "Laptop description",
                            Name = "Laptop 1",
                            Price = 7999f,
                            Rating = 4.2m,
                            Stock = 500
                        },
                        new
                        {
                            Id = new Guid("8f49d0f9-b3c9-4677-8293-85b7ee960db8"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3725),
                            Description = "Laptop description",
                            Name = "Laptop 2",
                            Price = 8999f,
                            Rating = 4.3m,
                            Stock = 400
                        },
                        new
                        {
                            Id = new Guid("a2870186-5d8d-4f11-9b76-b72a41c77b36"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3734),
                            Description = "Laptop description",
                            Name = "Laptop 3",
                            Price = 9999f,
                            Rating = 4.6m,
                            Stock = 300
                        },
                        new
                        {
                            Id = new Guid("855184b0-27d0-4b0f-a4e2-64954956b687"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3736),
                            Description = "Laptop description",
                            Name = "Laptop 4",
                            Price = 10999f,
                            Rating = 3.7m,
                            Stock = 250
                        },
                        new
                        {
                            Id = new Guid("0456675b-eca9-4d43-b130-f28fc466d78e"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3738),
                            Description = "Laptop description",
                            Name = "Laptop 5",
                            Price = 11999f,
                            Rating = 4.3m,
                            Stock = 350
                        },
                        new
                        {
                            Id = new Guid("c16ac1bf-3a29-445e-ba89-7d8d0d77d71e"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3739),
                            Description = "Laptop description",
                            Name = "Laptop 6",
                            Price = 12999f,
                            Rating = 4.5m,
                            Stock = 570
                        },
                        new
                        {
                            Id = new Guid("f34af61d-56d8-4f42-bd1a-7e2c5832a961"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3741),
                            Description = "Laptop description",
                            Name = "Laptop 7",
                            Price = 13999f,
                            Rating = 2.8m,
                            Stock = 670
                        },
                        new
                        {
                            Id = new Guid("46ac94bb-390f-4be6-8a0a-2d94bf9e68c1"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3743),
                            Description = "Laptop description",
                            Name = "Laptop 8",
                            Price = 14999f,
                            Rating = 3.6m,
                            Stock = 580
                        },
                        new
                        {
                            Id = new Guid("0a8772cc-a650-4ce8-a674-5d3b312a2bc4"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3745),
                            Description = "Laptop description",
                            Name = "Laptop 9",
                            Price = 15999f,
                            Rating = 4.7m,
                            Stock = 940
                        },
                        new
                        {
                            Id = new Guid("80fbe55b-1d37-4c40-9c8e-864ab537dd5b"),
                            CategoryId = new Guid("12108f44-2aa8-4a5d-bf2d-dc91e552e017"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3747),
                            Description = "Laptop description",
                            Name = "Laptop 10",
                            Price = 16999f,
                            Rating = 4.2m,
                            Stock = 130
                        },
                        new
                        {
                            Id = new Guid("9b0cd04e-b3b9-45c7-bd16-1e4537baae56"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3751),
                            Description = "Book description",
                            Name = "Book 1",
                            Price = 50f,
                            Rating = 4.2m,
                            Stock = 500
                        },
                        new
                        {
                            Id = new Guid("2dd779b5-5dfb-4039-8464-f67c747348ed"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3753),
                            Description = "Book description",
                            Name = "Book 2",
                            Price = 60f,
                            Rating = 4.3m,
                            Stock = 400
                        },
                        new
                        {
                            Id = new Guid("203a23f0-42e9-4399-9015-c87cd71ca3d2"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3755),
                            Description = "Book description",
                            Name = "Book 3",
                            Price = 70f,
                            Rating = 4.6m,
                            Stock = 300
                        },
                        new
                        {
                            Id = new Guid("f1350811-8d93-47e4-b040-8e24c51ab964"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3757),
                            Description = "Book description",
                            Name = "Book 4",
                            Price = 75f,
                            Rating = 3.7m,
                            Stock = 250
                        },
                        new
                        {
                            Id = new Guid("8e391020-67c4-4710-821e-6ba0adca8403"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3758),
                            Description = "Book description",
                            Name = "Book 5",
                            Price = 25f,
                            Rating = 4.3m,
                            Stock = 350
                        },
                        new
                        {
                            Id = new Guid("fd26fc86-872b-47c8-b6e5-5a9270196428"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3760),
                            Description = "Book description",
                            Name = "Book 6",
                            Price = 20f,
                            Rating = 4.5m,
                            Stock = 570
                        },
                        new
                        {
                            Id = new Guid("3cc91dea-5506-4946-9341-8e11d6bd0b5c"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3762),
                            Description = "Book description",
                            Name = "Book 7",
                            Price = 130f,
                            Rating = 2.8m,
                            Stock = 670
                        },
                        new
                        {
                            Id = new Guid("780bee16-aa3e-452d-9589-d4b2e24ea6eb"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3764),
                            Description = "Book description",
                            Name = "Book 8",
                            Price = 250f,
                            Rating = 3.6m,
                            Stock = 580
                        },
                        new
                        {
                            Id = new Guid("ca74ed7b-808b-456f-b71b-711e1ae2ed60"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3767),
                            Description = "Book description",
                            Name = "Book 9",
                            Price = 300f,
                            Rating = 4.7m,
                            Stock = 940
                        },
                        new
                        {
                            Id = new Guid("2245af99-67f5-4054-a953-945efbf1c023"),
                            CategoryId = new Guid("8d1f9698-77a6-4e0d-b399-384f6fbb736a"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3769),
                            Description = "Book description",
                            Name = "Book 10",
                            Price = 199f,
                            Rating = 4.2m,
                            Stock = 130
                        },
                        new
                        {
                            Id = new Guid("b9aa926d-617e-4c68-b192-fd511afa23c9"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3771),
                            Description = "Shoe description",
                            Name = "Shoe 1",
                            Price = 500f,
                            Rating = 4.2m,
                            Stock = 500
                        },
                        new
                        {
                            Id = new Guid("a74a3b1b-2734-47b1-ad19-8f2e7cd95543"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3773),
                            Description = "Shoe description",
                            Name = "Shoe 2",
                            Price = 600f,
                            Rating = 4.3m,
                            Stock = 400
                        },
                        new
                        {
                            Id = new Guid("bc48897f-a496-4e30-aff3-64107534dbf6"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3774),
                            Description = "Shoe description",
                            Name = "Shoe 3",
                            Price = 700f,
                            Rating = 4.6m,
                            Stock = 300
                        },
                        new
                        {
                            Id = new Guid("dd693237-743f-416a-8dba-fe3a370bbeeb"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3776),
                            Description = "Shoe description",
                            Name = "Shoe 4",
                            Price = 750f,
                            Rating = 3.7m,
                            Stock = 250
                        },
                        new
                        {
                            Id = new Guid("050461bd-313e-433e-9aec-74dc87b2fd8c"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3778),
                            Description = "Shoe description",
                            Name = "Shoe 5",
                            Price = 250f,
                            Rating = 4.3m,
                            Stock = 350
                        },
                        new
                        {
                            Id = new Guid("4a2a7ac3-b72b-4aff-8bb4-6dd566af554b"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3779),
                            Description = "Shoe description",
                            Name = "Shoe 6",
                            Price = 200f,
                            Rating = 4.5m,
                            Stock = 570
                        },
                        new
                        {
                            Id = new Guid("34b47478-7a2a-4a88-99a2-472afb148106"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3783),
                            Description = "Shoe description",
                            Name = "Shoe 7",
                            Price = 1300f,
                            Rating = 2.8m,
                            Stock = 670
                        },
                        new
                        {
                            Id = new Guid("deeca117-c11f-421c-8a2e-6d1706231c6b"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3785),
                            Description = "Shoe description",
                            Name = "Shoe 8",
                            Price = 2500f,
                            Rating = 3.6m,
                            Stock = 580
                        },
                        new
                        {
                            Id = new Guid("7417ca5c-604f-4c49-ba89-814e6c9b6f7b"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3786),
                            Description = "Shoe description",
                            Name = "Shoe 9",
                            Price = 3000f,
                            Rating = 4.7m,
                            Stock = 940
                        },
                        new
                        {
                            Id = new Guid("32b5a580-fb3d-4212-a0d3-af54a69434a2"),
                            CategoryId = new Guid("19cdfaee-e22f-48a1-b172-b9a9f92e9214"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3788),
                            Description = "Shoe description",
                            Name = "Shoe 10",
                            Price = 1990f,
                            Rating = 4.2m,
                            Stock = 130
                        },
                        new
                        {
                            Id = new Guid("3ccf2335-5937-40f1-8c5a-ce4fc7cced77"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3790),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 1",
                            Price = 100f,
                            Rating = 4.2m,
                            Stock = 500
                        },
                        new
                        {
                            Id = new Guid("df65edfe-7b2c-49ae-bb3d-cbc6de5f150a"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3792),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 2",
                            Price = 70f,
                            Rating = 4.3m,
                            Stock = 400
                        },
                        new
                        {
                            Id = new Guid("4e21c3f3-6087-4077-8a4e-2552a10302bb"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3794),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 3",
                            Price = 80f,
                            Rating = 4.6m,
                            Stock = 300
                        },
                        new
                        {
                            Id = new Guid("c4cada5f-b05a-4f7c-9f01-07726651b133"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3795),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 4",
                            Price = 40f,
                            Rating = 3.7m,
                            Stock = 250
                        },
                        new
                        {
                            Id = new Guid("e9438e5f-8569-4a82-bb2c-5013965b365e"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3799),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 5",
                            Price = 150f,
                            Rating = 4.3m,
                            Stock = 350
                        },
                        new
                        {
                            Id = new Guid("2c9d379e-b50f-4c3b-8259-105cf29ac623"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3800),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 6",
                            Price = 200f,
                            Rating = 4.5m,
                            Stock = 570
                        },
                        new
                        {
                            Id = new Guid("adcf151c-c6bf-47bb-a764-7072099249e8"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3802),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 7",
                            Price = 300f,
                            Rating = 2.8m,
                            Stock = 670
                        },
                        new
                        {
                            Id = new Guid("9b48190a-846f-4622-bd2a-21aff3ebcdd4"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3804),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 8",
                            Price = 200f,
                            Rating = 3.6m,
                            Stock = 580
                        },
                        new
                        {
                            Id = new Guid("dd5c5239-b441-48fc-8cb5-c9757cabdb79"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3806),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 9",
                            Price = 300f,
                            Rating = 4.7m,
                            Stock = 940
                        },
                        new
                        {
                            Id = new Guid("37c154ac-8946-4888-b9e3-672f3047967b"),
                            CategoryId = new Guid("11d6f34c-52c5-408c-8d83-e93a51548025"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3807),
                            Description = "Cosmetic description",
                            Name = "Cosmetic 10",
                            Price = 190f,
                            Rating = 4.2m,
                            Stock = 130
                        },
                        new
                        {
                            Id = new Guid("796a535e-e944-46d5-ba7a-6b478a0ca66d"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3809),
                            Description = "Furniture description",
                            Name = "Furniture 1",
                            Price = 1000f,
                            Rating = 4.2m,
                            Stock = 500
                        },
                        new
                        {
                            Id = new Guid("436df773-59d4-49ef-ba77-822d4bf55aff"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3811),
                            Description = "Furniture description",
                            Name = "Furniture 2",
                            Price = 700f,
                            Rating = 4.3m,
                            Stock = 400
                        },
                        new
                        {
                            Id = new Guid("31f9820b-af16-48ed-b494-237a29b6fa30"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3814),
                            Description = "Furniture description",
                            Name = "Furniture 3",
                            Price = 800f,
                            Rating = 4.6m,
                            Stock = 300
                        },
                        new
                        {
                            Id = new Guid("ccfae51d-5bbf-4980-9b95-4f9950a8f985"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3816),
                            Description = "Furniture description",
                            Name = "Furniture 4",
                            Price = 450f,
                            Rating = 3.7m,
                            Stock = 250
                        },
                        new
                        {
                            Id = new Guid("5e0925b9-f20f-45a6-b713-94ac0043e2ba"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3818),
                            Description = "Furniture description",
                            Name = "Furniture 5",
                            Price = 1550f,
                            Rating = 4.3m,
                            Stock = 350
                        },
                        new
                        {
                            Id = new Guid("9c8544d0-7e83-40c3-b38a-ce9dd0b9a1f6"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3819),
                            Description = "Furniture description",
                            Name = "Furniture 6",
                            Price = 2050f,
                            Rating = 4.5m,
                            Stock = 570
                        },
                        new
                        {
                            Id = new Guid("ec7f7a3e-07dc-4fb7-a124-4a69ed47b350"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3845),
                            Description = "Furniture description",
                            Name = "Furniture 7",
                            Price = 3500f,
                            Rating = 2.8m,
                            Stock = 670
                        },
                        new
                        {
                            Id = new Guid("c337d5c5-748d-496d-93c1-8bcdf8c7d840"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3847),
                            Description = "Furniture description",
                            Name = "Furniture 8",
                            Price = 2500f,
                            Rating = 3.6m,
                            Stock = 580
                        },
                        new
                        {
                            Id = new Guid("185e63b6-863d-46e4-8302-36e3246a3a03"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3849),
                            Description = "Furniture description",
                            Name = "Furniture 9",
                            Price = 3500f,
                            Rating = 4.7m,
                            Stock = 940
                        },
                        new
                        {
                            Id = new Guid("2b6ed6b5-b0ea-465e-b506-fa5564881847"),
                            CategoryId = new Guid("252feae8-fa30-47b7-9554-91eb2025eebb"),
                            CreatedDate = new DateTime(2023, 8, 31, 14, 27, 53, 981, DateTimeKind.Local).AddTicks(3851),
                            Description = "Furniture description",
                            Name = "Furniture 10",
                            Price = 1950f,
                            Rating = 4.2m,
                            Stock = 130
                        });
                });

            modelBuilder.Entity("T_G.ECommerce.Entities.Concrete.Product", b =>
                {
                    b.HasOne("T_G.ECommerce.Entities.Concrete.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("T_G.ECommerce.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
